# Exercices {.unnumbered}

::: callout-important
Tous les exercices doivent être maitrisés **avec** et **sans** R.
:::

## Le vocabulaire de la statistique descriptive

::: {.callout-note icon=false}
## Exercice 1
1. Donner la définition d'une population ainsi que trois exemples.
2. Définir la notion d'unité statistique ou individu et donner trois exemples.
:::

::: {.callout-tip collapse="true"}
## Solution Exercice 1
coming.
:::

## Variables qualitatives

::: {.callout-note icon=false}
## Exercice 2
1. Donner la définition d'une population ainsi que trois exemples.
2. Définir la notion d'unité statistique ou individu et donner trois exemples.
:::

::: {.callout-tip collapse="true"}
## Solution Exercice 2
coming.
:::

::: {.callout-note icon=false}
## Exercice 3
1. Donner la définition d'une population ainsi que trois exemples.
2. Définir la notion d'unité statistique ou individu et donner trois exemples.
:::

::: {.callout-tip collapse="true"}
## Solution Exercice 3
coming.
:::

## Variables quantatives

::: {.callout-note icon=false}
## Exercice 4
1. Donner la définition d'une population ainsi que trois exemples.
2. Définir la notion d'unité statistique ou individu et donner trois exemples.
:::

::: {.callout-tip collapse="true"}
## Solution Exercice 4
coming.
:::

::: {.callout-note icon=false}
## Exercice 5
1. Donner la définition d'une population ainsi que trois exemples.
2. Définir la notion d'unité statistique ou individu et donner trois exemples.
:::

::: {.callout-tip collapse="true"}
## Solution Exercice 5
coming.
:::