<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Antoine Géré">

<title>Du palais à la p-value</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="td_palais_p-value_files/libs/clipboard/clipboard.min.js"></script>
<script src="td_palais_p-value_files/libs/quarto-html/quarto.js"></script>
<script src="td_palais_p-value_files/libs/quarto-html/popper.min.js"></script>
<script src="td_palais_p-value_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="td_palais_p-value_files/libs/quarto-html/anchor.min.js"></script>
<link href="td_palais_p-value_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="td_palais_p-value_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="td_palais_p-value_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="td_palais_p-value_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="td_palais_p-value_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="td_palais_p-value_files/libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="td_palais_p-value_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/datatables-binding-0.34.0/datatables.js"></script>

<script src="td_palais_p-value_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="td_palais_p-value_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="td_palais_p-value_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="td_palais_p-value_files/libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>

<link href="td_palais_p-value_files/libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/selectize-0.12.0/selectize.min.js"></script>

<link href="td_palais_p-value_files/libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="td_palais_p-value_files/libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sujets-de-mesures" id="toc-sujets-de-mesures" class="nav-link active" data-scroll-target="#sujets-de-mesures">Sujets de mesures</a></li>
  <li><a href="#dispersion-des-résultats" id="toc-dispersion-des-résultats" class="nav-link" data-scroll-target="#dispersion-des-résultats">Dispersion des résultats</a></li>
  <li><a href="#experience-illustratrice" id="toc-experience-illustratrice" class="nav-link" data-scroll-target="#experience-illustratrice">Experience illustratrice</a></li>
  <li><a href="#tests-discriminatifs" id="toc-tests-discriminatifs" class="nav-link" data-scroll-target="#tests-discriminatifs">Tests discriminatifs</a>
  <ul>
  <li><a href="#test-par-paire" id="toc-test-par-paire" class="nav-link" data-scroll-target="#test-par-paire">Test par Paire</a>
  <ul class="collapse">
  <li><a href="#principe-et-protocole" id="toc-principe-et-protocole" class="nav-link" data-scroll-target="#principe-et-protocole">Principe et Protocole</a></li>
  <li><a href="#avantages-et-indications" id="toc-avantages-et-indications" class="nav-link" data-scroll-target="#avantages-et-indications">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique" id="toc-exploitation-statistique" class="nav-link" data-scroll-target="#exploitation-statistique">Exploitation Statistique</a></li>
  <li><a href="#application" id="toc-application" class="nav-link" data-scroll-target="#application">Application</a></li>
  </ul></li>
  <li><a href="#test-duo-trio" id="toc-test-duo-trio" class="nav-link" data-scroll-target="#test-duo-trio">Test Duo-Trio</a>
  <ul class="collapse">
  <li><a href="#principe-et-protocole-1" id="toc-principe-et-protocole-1" class="nav-link" data-scroll-target="#principe-et-protocole-1">Principe et Protocole</a></li>
  <li><a href="#avantages-et-indications-1" id="toc-avantages-et-indications-1" class="nav-link" data-scroll-target="#avantages-et-indications-1">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique-1" id="toc-exploitation-statistique-1" class="nav-link" data-scroll-target="#exploitation-statistique-1">Exploitation Statistique</a></li>
  <li><a href="#application-1" id="toc-application-1" class="nav-link" data-scroll-target="#application-1">Application</a></li>
  </ul></li>
  <li><a href="#test-triangulaire" id="toc-test-triangulaire" class="nav-link" data-scroll-target="#test-triangulaire">Test Triangulaire</a>
  <ul class="collapse">
  <li><a href="#principe-et-protocole-2" id="toc-principe-et-protocole-2" class="nav-link" data-scroll-target="#principe-et-protocole-2">Principe et Protocole</a></li>
  <li><a href="#avantages-et-indications-2" id="toc-avantages-et-indications-2" class="nav-link" data-scroll-target="#avantages-et-indications-2">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique-2" id="toc-exploitation-statistique-2" class="nav-link" data-scroll-target="#exploitation-statistique-2">Exploitation Statistique</a></li>
  <li><a href="#application-2" id="toc-application-2" class="nav-link" data-scroll-target="#application-2">Application</a></li>
  </ul></li>
  <li><a href="#test-p-parmi-n" id="toc-test-p-parmi-n" class="nav-link" data-scroll-target="#test-p-parmi-n">Test p parmi n</a>
  <ul class="collapse">
  <li><a href="#principe-et-protocole-3" id="toc-principe-et-protocole-3" class="nav-link" data-scroll-target="#principe-et-protocole-3">Principe et Protocole</a></li>
  <li><a href="#avantages-et-indications-3" id="toc-avantages-et-indications-3" class="nav-link" data-scroll-target="#avantages-et-indications-3">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique-3" id="toc-exploitation-statistique-3" class="nav-link" data-scroll-target="#exploitation-statistique-3">Exploitation Statistique</a></li>
  <li><a href="#application-3" id="toc-application-3" class="nav-link" data-scroll-target="#application-3">Application</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#tests-descriptifs" id="toc-tests-descriptifs" class="nav-link" data-scroll-target="#tests-descriptifs">Tests descriptifs</a>
  <ul>
  <li><a href="#test-dintensité" id="toc-test-dintensité" class="nav-link" data-scroll-target="#test-dintensité">Test d’intensité</a>
  <ul class="collapse">
  <li><a href="#principe-et-protocole-4" id="toc-principe-et-protocole-4" class="nav-link" data-scroll-target="#principe-et-protocole-4">Principe et protocole</a></li>
  <li><a href="#avantages-et-indications-4" id="toc-avantages-et-indications-4" class="nav-link" data-scroll-target="#avantages-et-indications-4">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique-4" id="toc-exploitation-statistique-4" class="nav-link" data-scroll-target="#exploitation-statistique-4">Exploitation Statistique</a></li>
  <li><a href="#application-4" id="toc-application-4" class="nav-link" data-scroll-target="#application-4">Application</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#test-de-classement" id="toc-test-de-classement" class="nav-link" data-scroll-target="#test-de-classement">Test de classement</a>
  <ul>
  <li><a href="#principe-et-protocole-5" id="toc-principe-et-protocole-5" class="nav-link" data-scroll-target="#principe-et-protocole-5">Principe et protocole</a></li>
  <li><a href="#avantages-et-indications-5" id="toc-avantages-et-indications-5" class="nav-link" data-scroll-target="#avantages-et-indications-5">Avantages et Indications</a></li>
  <li><a href="#exploitation-statistique-5" id="toc-exploitation-statistique-5" class="nav-link" data-scroll-target="#exploitation-statistique-5">Exploitation Statistique</a></li>
  <li><a href="#application-5" id="toc-application-5" class="nav-link" data-scroll-target="#application-5">Application</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Du palais à la p-value</h1>
<p class="subtitle lead">Une première immersion dans l’analyse sensorielle</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Auteur·rice</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Antoine Géré <a href="mailto:a.gere@istom.fr" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://www.istom.fr/">ISTOM</a>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Date de publication</div>
    <div class="quarto-title-meta-contents">
      <p class="date">28 mars 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<hr>
<div class="columns">
<div class="column" style="width:70%;">
<p>L’<strong>Analyse Sensorielle</strong> regroupe l’ensemble des protocoles scientifiques permettant de mesurer et d’interpréter les propriétés organoleptiques d’un produit. Contrairement aux outils de mesure classiques, l’Analyse Sensorielle place l’etre humain et ses sens au coeur du disposititif de mesure.</p>
<p>Émergée dans les années 1960 aux États-Unis, cette discipline est devenue le complément indispensable des analyses physico-chimiques traditionnelles. Elle permet de valider ce qu’aucune machine ne peut totalement quantifier : la perception globale et le plaisir de l’utilisateur.</p>
</div><div class="column" style="width:30%;">
<p><img src="img/analyse_senso.jpg" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
<section id="sujets-de-mesures" class="level2">
<h2 class="anchored" data-anchor-id="sujets-de-mesures">Sujets de mesures</h2>
<p>En analyse sensorielle, les tests sont réalisés par des personnes que l’on nomme sujets. On va chercher chez ces sujets certaines caractéristiques :</p>
<ul>
<li><p><strong>fiabilité</strong> : aptitude à donner des mesures très voisine lors de l’application du même signal d’entrée</p></li>
<li><p><strong>répétabilité</strong> : réponses fidèles quand l’analyse sensorielle est faite dans les mêmes conditions (même salle, mêmes tests…)</p></li>
<li><p><strong>reproductibilité</strong> : répétition faite en faisant varier certaines conditions d’une répétition à l’autre (lieux, résultats inter laboratoires…)</p></li>
<li><p><strong>justesse</strong> : moyenne des indications données et très voisine de la valeur vraie de la grandeur à mesurer</p></li>
</ul>
</section>
<section id="dispersion-des-résultats" class="level2">
<h2 class="anchored" data-anchor-id="dispersion-des-résultats">Dispersion des résultats</h2>
<p>La variabilité observée lors d’une évaluation sensorielle provient de deux sources principales : le produit lui-même et le facteur humain (les sujets).</p>
<ul>
<li><p>La <strong>variabilité liée aux produits</strong></p>
<ul>
<li><p>Pour obtenir des conclusions fiables, il est crucial de maîtriser la représentativité des échantillons.</p></li>
<li><p>On cherche à présenter des produits identiques au sein d’un même lot pour ne mesurer que la différence voulue.</p></li>
</ul></li>
<li><p>La <strong>variabilité liée aux sujets</strong> (Facteur Humain)</p>
<ul>
<li><p>La variance inter-individuelle (entre les sujets), elle reflète les différences de perception ou d’utilisation de l’échelle d’un juge à l’autre.</p></li>
<li><p>La variance intra-individuelle (au sein d’un même sujet), elle mesure le manque de répétabilité d’un juge (sa capacité à donner la même réponse pour un même produit lors de deux séances différentes).</p></li>
</ul></li>
</ul>
</section>
<section id="experience-illustratrice" class="level2">
<h2 class="anchored" data-anchor-id="experience-illustratrice">Experience illustratrice</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Le <strong>Bissap Istomien</strong> est une boisson emblématique appréciée par les étudiant-es. Afin d’améliorer la recette, nous testons l’ajout de <strong>vanille</strong>.</p>
<p>L’objectif est de déterminer si cet ajout crée une différence gustative perceptible et d’en caractériser l’intensité.</p>
<p>Nous allons construire son profil sensoriel. Il servira de support pour illustrer les différents tests présentés plus bas.</p>
</div><div class="column" style="width:40%;">
<p><img src="img/bissap.jpg" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
</section>
<section id="tests-discriminatifs" class="level2">
<h2 class="anchored" data-anchor-id="tests-discriminatifs">Tests discriminatifs</h2>
<p>Les <strong>tests discriminatifs</strong> sont utilisés si l’enjeu est simplement de détecter une différence entre des échantillons,</p>
<p>Ils ont pour mission exclusive de déceler la présence ou l’absence d’une différence sensorielle entre deux produits. Elles sont particulièrement indiquées lorsque les écarts sont supposés faibles ou inconnus.</p>
<p>Si ces tests permettent de dire si une différence existe, ils ne permettent en aucun cas de la nommer (identifier sa nature) ni de la mesurer (quantifier son intensité).</p>
<section id="test-par-paire" class="level3">
<h3 class="anchored" data-anchor-id="test-par-paire">Test par Paire</h3>
<section id="principe-et-protocole" class="level4">
<h4 class="anchored" data-anchor-id="principe-et-protocole">Principe et Protocole</h4>
<p>Le test par paire est la méthode de discrimination la plus élémentaire. Elle consiste à présenter deux échantillons simultanément pour répondre à une question précise.</p>
<p>Le sujet reçoit deux échantillons codés (A et B). Le protocole repose sur un choix forcé (le sujet doit obligatoirement désigner un produit). On présente les deux combinaisons de manière égale, c’est à dire AB et BA.</p>
<p>On distingue deux variantes principales :</p>
<ul>
<li><p>Test Unilatéral : On demande au sujet lequel des deux produits est le plus intense sur un critère précis (ex: “Lequel est le plus sucré ?”).</p></li>
<li><p>Test de Préférence : On demande au sujet quel produit il préfère.</p></li>
</ul>
<p>Le choix s’effectue ici entre seulement deux options, donc :</p>
<ul>
<li><p>Probabilité de succès par hasard (p) : 1/2 (50 %).</p></li>
<li><p>Probabilité d’échec par hasard (q) : 1/2 (50 %).</p></li>
</ul>
</section>
<section id="avantages-et-indications" class="level4">
<h4 class="anchored" data-anchor-id="avantages-et-indications">Avantages et Indications</h4>
<p>C’est le test le plus accessible, tant pour l’organisateur que pour le sujet.</p>
<p>Très peu d’effort cognitif requis. Il est idéal pour des sujets non entraînés, ou des produits très complexes où une comparaison à trois (Triangle) saturerait les sens.</p>
<p>Cependant sa puissance statistique est faible. Comme la probabilité de réussir par hasard est élevée (50 %), il faut un panel plus large (souvent n&gt;30) pour obtenir un résultat significatif par rapport au test triangulaire.</p>
</section>
<section id="exploitation-statistique" class="level4">
<h4 class="anchored" data-anchor-id="exploitation-statistique">Exploitation Statistique</h4>
<p>L’analyse repose sur la comparaison du nombre de réponses obtenues avec les valeurs de la Loi Binomiale (p=0,5).</p>
<ul>
<li><strong>Hypothèse Nulle</strong> <span class="math inline">\(H_0\)</span> : Les deux produits sont perçus comme identiques (ou aimés de façon égale), le choix est dû au hasard.</li>
</ul>
<p><span class="math display">\[H_0: \quad p = \frac12\]</span></p>
<ul>
<li><strong>Hypothèse Alternative</strong> <span class="math inline">\(H_1\)</span> : Un produit est significativement distingué ou préféré. <span class="math display">\[H_1: \quad p &gt; \frac12\]</span></li>
</ul>
<p>On utilise le test binomial exact. Si la p-value est inférieure à <span class="math inline">\(\alpha\)</span>, on conclut à une différence ou préférence significative.</p>
</section>
<section id="application" class="level4">
<h4 class="anchored" data-anchor-id="application">Application</h4>
<p><strong>Test par Paire (Bissap Nature vs Vanille)</strong></p>
<p>L’objectif est de vérifier si l’ajout de vanille est détecté par les étudiants de l’ISTOM lors d’une comparaison directe.)</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Test par Paire en pratique
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le protocole est le suivant :</p>
<ul>
<li><p>Échantillons : Un verre de Bissap “Nature” (A) et un verre de Bissap “Vanille” (B).</p></li>
<li><p>Chaque sujet reçoit les deux verres simultanément.</p></li>
<li><p>Pour éviter l’effet de premier échantillon, la moitié des sujets goûte AB et l’autre moitié goûte BA.</p></li>
<li><p>Question posée au sujet : <strong>« Lequel de ces deux produits est le plus aromatisé ? »</strong></p></li>
</ul>
<p><strong>La base de données</strong> simule les réponses de 60 étudiants de l’ISTOM. Elle contient les variables suivantes :</p>
<ul>
<li><p><code>id</code> : Identifiant unique du sujet</p></li>
<li><p><code>expertise</code> : Profil du sujet (Expert ou Novice).</p></li>
<li><p><code>ordre</code> : La séquence de présentation (AB ou BA).</p></li>
<li><p><code>reussite</code> : Résultat (reussi ou echec).</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">789</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n_etudiants <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data_paire <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n_etudiants,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">expertise =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Expert"</span>, <span class="st">"Novice"</span>), n_etudiants, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.7</span>)),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordre =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Nature-Vanille"</span>, <span class="st">"Vanille-Nature"</span>), n_etudiants, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>data_paire<span class="sc">$</span>reussite <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(exp) {</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  prob <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(exp <span class="sc">==</span> <span class="st">"Expert"</span>, <span class="fl">0.78</span>, <span class="fl">0.63</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, prob)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(res <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"reussi"</span>, <span class="st">"echec"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>}, data_paire<span class="sc">$</span>expertise)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-fdd78d17fa33b69020c9" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-fdd78d17fa33b69020c9">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td><\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"1\" data-max=\"60\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","caption":"<caption>Test par Paire sur le Bissap<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60],["Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Expert","Expert","Expert","Novice","Novice","Novice","Expert","Novice","Expert","Novice","Novice","Novice","Expert","Novice","Expert","Expert","Novice","Novice","Novice"],["Nature-Vanille","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Nature-Vanille","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Nature-Vanille","Vanille-Nature","Nature-Vanille","Vanille-Nature","Vanille-Nature","Nature-Vanille","Nature-Vanille","Vanille-Nature","Nature-Vanille","Nature-Vanille","Vanille-Nature","Nature-Vanille","Nature-Vanille","Nature-Vanille","Vanille-Nature","Nature-Vanille","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Nature-Vanille","Nature-Vanille","Nature-Vanille","Vanille-Nature","Nature-Vanille","Nature-Vanille","Vanille-Nature","Nature-Vanille","Nature-Vanille","Vanille-Nature","Vanille-Nature","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Vanille-Nature","Nature-Vanille","Vanille-Nature","Nature-Vanille"],["reussi","echec","echec","echec","reussi","echec","echec","echec","echec","reussi","reussi","reussi","reussi","reussi","reussi","echec","reussi","echec","reussi","reussi","echec","reussi","echec","reussi","echec","reussi","reussi","reussi","reussi","reussi","reussi","echec","echec","reussi","echec","reussi","echec","reussi","reussi","reussi","echec","reussi","reussi","reussi","reussi","reussi","reussi","reussi","reussi","reussi","reussi","echec","reussi","reussi","reussi","echec","reussi","reussi","echec","echec"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>expertise<\/th>\n      <th>ordre<\/th>\n      <th>reussite<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"className":"dt-right","targets":1},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"expertise","targets":2},{"name":"ordre","targets":3},{"name":"reussite","targets":4}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><strong>Test Binomial</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>n_reussi <span class="ot">=</span> <span class="fu">sum</span>(data_paire<span class="sc">$</span>reussite <span class="sc">==</span> <span class="st">"reussi"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>n_total <span class="ot">=</span> <span class="fu">nrow</span>(data_paire)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> n_reussi, <span class="at">n =</span> n_total, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  n_reussi and n_total
number of successes = 39, number of trials = 60, p-value = 0.01367
alternative hypothesis: true probability of success is greater than 0.5
95 percent confidence interval:
 0.5363726 1.0000000
sample estimates:
probability of success 
                  0.65 </code></pre>
</div>
</div>
<ul>
<li><p>Nombre de succès (17 / 30) : Un peu plus de la moitié des étudiants ( 56,7 % ) ont désigné le produit vanillé.</p></li>
<li><p>La p-value <span class="math inline">\(0,2923\)</span>. C’est l’indicateur majeur. Elle est largement supérieure au seuil classique <span class="math inline">\(\alpha\)</span> de <span class="math inline">\(0,05\)</span> (5 %). On rejette donc l’hypothèse nulle.</p></li>
</ul>
<p><strong>Influence de l’Expertise sur la réussite</strong></p>
<p>Il est intéressant de voir si les “Experts” ont effectivement mieux détecté la vanille que les “Novices”. Pour cela, on utilise un tableau de contingence et un test de Fisher (plus robuste que le Chi-deux sur de petits effectifs).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tableau croisé</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>table_exp <span class="ot">=</span> <span class="fu">table</span>(data_paire<span class="sc">$</span>expertise, data_paire<span class="sc">$</span>reussite)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(table_exp)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         echec reussi
  Expert     1     10
  Novice    20     29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Fisher</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(table_exp)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  table_exp
p-value = 0.07786
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.003189801 1.195874151
sample estimates:
odds ratio 
 0.1486264 </code></pre>
</div>
</div>
<p>La p-value est de 0,07786. Elle est supérieure à 0,05. On ne peut pas rejeter l’hypothèse nulle au seuil de 5%. On conclut qu’il n’y a pas de différence significative entre les experts et les novices au seuil de 5%.</p>
<p>On peut ensuite essayer de visualiser cette expertise. Ce graphique permetra de comparer visuellement le taux de succès entre les deux groupes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_paire, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> expertise, <span class="at">fill =</span> reussite)) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"reussi"</span> <span class="ot">=</span> <span class="st">"#2ecc71"</span>, <span class="st">"echec"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Taux de réussite selon le niveau d'expertise"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Groupe"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Pourcentage de réussite"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Résultat"</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">1.5</span>, <span class="at">y =</span> <span class="fl">0.52</span>, <span class="at">label =</span> <span class="st">"Seuil du hasard (50%)"</span>) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="td_palais_p-value_files/figure-html/plot-expertise-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Calcul de la distance sensorielle (d prime)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensR)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">discrim</span>(n_reussi, n_total, <span class="at">method =</span> <span class="st">"twoAFC"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimates for the twoAFC discrimination protocol with 39 correct
answers in 60 trials. One-sided p-value and 95 % two-sided confidence
intervals are based on the 'exact' binomial test. 

        Estimate Std. Error   Lower  Upper
pc        0.6500    0.06158 0.51597 0.7687
pd        0.3000    0.12315 0.03194 0.5373
d-prime   0.5449    0.23510 0.05663 1.0387

Result of difference test:
'exact' binomial test:  p-value = 0.01367 
Alternative hypothesis: d-prime is greater than 0 </code></pre>
</div>
</div>
<p>Ici d-prime (d′) est égale à 0,2374.</p>
<p>C’est la distance sensorielle. Une valeur de 0,24 est extrêmement faible. En analyse sensorielle, on considère qu’une différence commence à être intéressante au-delà de 1 et qu’elle est évidente au-delà de 2.</p>
</section>
</section>
<section id="test-duo-trio" class="level3">
<h3 class="anchored" data-anchor-id="test-duo-trio">Test Duo-Trio</h3>
<section id="principe-et-protocole-1" class="level4">
<h4 class="anchored" data-anchor-id="principe-et-protocole-1">Principe et Protocole</h4>
<p>Le test Duo-Trio est une épreuve de différence où l’on présente au juge un échantillon identifié comme Témoin (R), suivi de deux échantillons codés (A et B). L’un des deux échantillons codés est identique au témoin.</p>
<p>La mission du juge est de répondre à la question : <strong>« Lequel de ces deux échantillons est identique au témoin ? »</strong></p>
<p>Il existe quatre ordres de présentation possibles, selon que le témoin est le produit A ou le produit B :</p>
<ul>
<li><p>Si A est le témoin : A (témoin) suivi de {A, B} ou A (témoin) suivi de {B, A}.</p></li>
<li><p>Si B est le témoin : B (témoin) suivi de {A, B} ou B (témoin) suivi de {B, A}.</p></li>
</ul>
<p>Contrairement au test triangulaire (cf prochain paragraphe), le choix s’effectue ici entre seulement deux options :</p>
<ul>
<li><p>Probabilité de succès par hasard (p) : 1/2 (soit 50 %).</p></li>
<li><p>Probabilité d’échec par hasard (q) : 1/2 (soit 50 %).</p></li>
</ul>
</section>
<section id="avantages-et-indications-1" class="level4">
<h4 class="anchored" data-anchor-id="avantages-et-indications-1">Avantages et Indications</h4>
<p>Le test Duo-Trio est souvent privilégié dans les situations suivantes :</p>
<p>Ce test est adapté pour les produits complexes ou agressifs. Comme le sujet connaît déjà la référence (le témoin), l’effort cognitif et sensoriel est moindre, ce qui limite la saturation.</p>
</section>
<section id="exploitation-statistique-1" class="level4">
<h4 class="anchored" data-anchor-id="exploitation-statistique-1">Exploitation Statistique</h4>
<p><strong>Définition de l’Hypothèse Nulle ( <span class="math inline">\(H_0\)</span> )</strong></p>
<p>L’hypothèse nulle postule qu’il n’y a aucune différence sensorielle perceptible entre l’échantillon témoin <span class="math inline">\((R)\)</span> et les échantillons présentés. En d’autres termes les deux produits sont identiques, la probabilité de désigner l’échantillon correct est uniquement due au hasard. D’un point de vue purement statstatistique : <span class="math display">\[H_0 \ : \  p= 1/2\]</span></p>
<p><strong>Définition de l’Hypothèse Alternative ( <span class="math inline">\(H_1\)</span> )</strong></p>
<p>C’est l’hypothèse que nous cherchez généralement à prouver. Elle postule qu’il existe une différence réelle. En d’autres termes les produits sont perçus comme différents, la probabilité de réussite est significativement supérieure au hasard. D’un point de vue purement statistique : <span class="math display">\[H_1 \ : \ p &gt; 1/ 2\]</span></p>
<p>Les résultats sont analysés via la loi binomiale. On compare le nombre de réponses correctes observées au nombre minimal requis pour atteindre une significativité statistique (souvent fixée à <span class="math inline">\(\alpha= 5\%\)</span>).</p>
</section>
<section id="application-1" class="level4">
<h4 class="anchored" data-anchor-id="application-1">Application</h4>
<p>Nous allons utiliser le Test Duo-Trio :</p>
<ul>
<li><p>Le sujet goûte un échantillon de référence.</p></li>
<li><p>Il goûte ensuite deux échantillons codés, dont l’un est identique à l’échantillon de référence</p></li>
<li><p>Question posée : <strong>Lequel des deux échantillons codés est identique au témoin ?</strong></p></li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Test Duo-Trio en pratique
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>L’objectif de l’étude</strong> est de déterminer s’il existe une différence gustative perceptible entre les deux recettes de Bissap suiavntes :</p>
<ul>
<li><p>Produit A : Recette classique.</p></li>
<li><p>Produit B : Recette avec ajout de vanille.</p></li>
</ul>
<p>Nous utilisons un <strong>test Duo-Trio</strong>. Chaque sujet reçoit un plateau de trois échantillons.</p>
<ul>
<li><p>Un témoin : Il est identifié. Pour cette étude, le témoin peut être soit A, soit B.</p></li>
<li><p>Les Échantillons prtent des des codes . L’un est identique au témoin, l’autre est différent.</p></li>
<li><p>Consigne donnée au juge : « Goûtez le témoin à gauche, puis les deux échantillons codés. Lequel des deux échantillons codés est identique au témoin ? »</p></li>
</ul>
<p><strong>La base de données</strong> simule les réponses de 60 étudiants de l’ISTOM. Elle contient les variables suivantes :</p>
<ul>
<li><p><code>id</code> : Identifiant unique du sujet</p></li>
<li><p><code>ordre</code> : La séquence de présentation (ex: A-AB signifie que le témoin est A, suivi des verres A puis B).</p></li>
<li><p><code>expertise</code> : Profil du sujet (Expert ou Novice).</p></li>
<li><p><code>fatigue</code> : Auto-évaluation de l’état de fatigue du sujet (1 à 5).</p></li>
<li><p><code>reussite</code> : Résultat (reussi ou echec).</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de sujets</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n_sujets <span class="ot">=</span> <span class="dv">60</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Les 4 combinaisons réelles du Duo-Trio</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Témoin - Premier Échantillon - Deuxième Échantillon</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ordres_possibles <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"A-AB"</span>, <span class="st">"A-BA"</span>, <span class="st">"B-AB"</span>, <span class="st">"B-BA"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du jeu de données</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>data_duotrio <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n_sujets,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># On tire au sort parmi les 4 ordres possibles</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordre =</span> <span class="fu">sample</span>(ordres_possibles, n_sujets, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">expertise =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Expert"</span>, <span class="st">"Novice"</span>), n_sujets, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)),</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">fatigue =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, n_sujets, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="co"># Score de fatigue auto-déclaré (sur 5)</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation des résultats</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>data_duotrio<span class="sc">$</span>reussite <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(exp) {</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  p_reussite <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(exp <span class="sc">==</span> <span class="st">"Expert"</span>, <span class="fl">0.75</span>, <span class="fl">0.55</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(<span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, p_reussite) <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"reussi"</span>, <span class="st">"echec"</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>}, data_duotrio<span class="sc">$</span>expertise)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-7f4e21e03c5674d0df9a" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-7f4e21e03c5674d0df9a">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td><\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"1\" data-max=\"60\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"1\" data-max=\"5\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","caption":"<caption>Test Duo-Trio sur le Bissap<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60],["B-AB","B-AB","B-AB","A-BA","B-AB","A-BA","A-BA","A-BA","B-AB","A-AB","B-BA","A-BA","A-BA","A-AB","A-BA","B-AB","B-BA","A-AB","B-AB","B-AB","A-AB","B-BA","A-AB","A-AB","A-AB","B-AB","B-BA","A-BA","B-AB","A-BA","A-AB","A-BA","B-AB","B-BA","A-BA","A-AB","B-AB","B-AB","A-AB","B-BA","B-AB","B-BA","A-BA","A-AB","B-AB","A-AB","A-AB","A-BA","B-AB","B-AB","B-BA","A-AB","B-AB","A-AB","B-AB","B-BA","A-BA","A-AB","A-BA","A-AB"],["Novice","Novice","Novice","Novice","Expert","Novice","Expert","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Expert","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Expert","Expert","Novice","Novice","Novice","Expert","Novice","Novice","Expert","Novice","Novice","Novice","Expert","Novice","Novice"],[5,3,2,5,5,3,2,2,2,4,2,2,4,4,1,3,3,1,3,5,2,3,2,5,5,3,4,4,4,5,3,1,2,1,2,5,3,4,4,1,4,1,3,4,3,5,4,4,4,1,2,3,4,3,1,5,5,2,3,5],["reussi","reussi","reussi","reussi","reussi","reussi","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","echec","echec","reussi","reussi","echec","reussi","reussi","echec","reussi","reussi","reussi","echec","echec","echec","echec","echec","reussi","echec","reussi","reussi","reussi","reussi","echec","reussi","reussi","reussi","echec","echec","echec","reussi","reussi","echec","echec","reussi","reussi","reussi","reussi","reussi","reussi","reussi","reussi","echec","reussi"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>ordre<\/th>\n      <th>expertise<\/th>\n      <th>fatigue<\/th>\n      <th>reussite<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"autoWidth":true,"columnDefs":[{"className":"dt-right","targets":[1,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"ordre","targets":2},{"name":"expertise","targets":3},{"name":"fatigue","targets":4},{"name":"reussite","targets":5}],"order":[],"orderClasses":false,"orderCellsTop":true}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n_sujets</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>n_reussi <span class="ot">=</span> <span class="fu">sum</span>(data_duotrio<span class="sc">$</span>reussite <span class="sc">==</span> <span class="st">"reussi"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>n_reussi</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37</code></pre>
</div>
</div>
<p>Il n’est pas suffisant de simplement observer le nombre personnes qui ont réussi (ici <code>n_reussi</code> sur 60) pour conclure. Est-ce que ces 27 personnes ont réellement senti la vanille, ou ont-elles simplement eu de la chance ?</p>
<p>Le test binomial exact est l’outil statistique qui permet de trancher. Il compare nos résultats réels à ce que le hasard pur aurait produit (une chance sur deux pour ce test Duo-Trio). On cherche à savoir si la proportion de bonnes réponses est significativement supérieure à 50 %.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(n_reussi, n_sujets, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  n_reussi and n_sujets
number of successes = 37, number of trials = 60, p-value = 0.04623
alternative hypothesis: true probability of success is greater than 0.5
95 percent confidence interval:
 0.5024333 1.0000000
sample estimates:
probability of success 
             0.6166667 </code></pre>
</div>
</div>
<p>Le panel a correctement identifié l’échantillon 37 fois sur 60. Cela représente un taux de succès de 61,6 %. On constate une nette progression par rapport au hasard théorique (50 %).</p>
<p>On peut lire que la <strong>p-value = 0.04623</strong>. C’est le chiffre pivot !</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interprétation de la p-value
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pour qu’un test soit statistiquement significatif, la p-value doit être inférieure au seuil <span class="math inline">\(\alpha\)</span> fixé.</p>
</div>
</div>
<p>On fixe ici <span class="math inline">\(\alpha\)</span> à <span class="math inline">\(5\%\)</span>. On peut lire que 0,04623 est inférieur à 0,05. Ce qui signifie qu’il y a moins de 5 % de chances que ce résultat soit dû au pur hasard. On rejette donc l’hypothèse nulle (H0).</p>
<p>Il est également donné l’intervalle de confiance à <span class="math inline">\(95\%\)</span>. La borne inférieure de l’intervalle est de 0,502 (soit 50,2 %). Comme cette valeur est supérieure à 0,50, cela confirme statistiquement que la capacité de détection du panel est supérieure au hasard, même si c’est de peu.</p>
<p><strong>Conclusion</strong> : Le test Duo-Trio est significatif. Avec un risque d’erreur inférieur à <span class="math inline">\(5\%\)</span>, nous pouvons affirmer que l’ajout de vanille dans le Bissap Istomien crée une différence gustative perceptible par les étudiants. Bien que la différence soit fine (le taux de réussite est de 61,6 %), elle est statistiquement validée. La recette à la vanille est donc officiellement distinguable de la recette classique.</p>
<p><strong>Pour aller plus loin :</strong></p>
<p>Au-delà de la simple réussite, nous pouvons chercher à quantifier la force de la différence perçue entre le Bissap classique et le Bissap vanille. On mesure la distance sensorielle, notée <span class="math inline">\(d^\prime\)</span>. On commence à renter dans un aspect plus descriptif.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensR)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">discrim</span>(n_reussi, n_sujets, <span class="at">method =</span> <span class="st">"duotrio"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimates for the duotrio discrimination protocol with 37 correct
answers in 60 trials. One-sided p-value and 95 % two-sided confidence
intervals are based on the 'exact' binomial test. 

        Estimate Std. Error Lower  Upper
pc        0.6167    0.06277   0.5 0.7393
pd        0.2333    0.12554   0.0 0.4786
d-prime   1.2198    0.38701   0.0 1.9530

Result of difference test:
'exact' binomial test:  p-value = 0.04623 
Alternative hypothesis: d-prime is greater than 0 </code></pre>
</div>
</div>
<p>Le <span class="math inline">\(d^\prime\)</span> est un indice de sensibilité indépendant de la taille du panel. Il se comme suit :</p>
<ul>
<li><p><span class="math inline">\(d^\prime = 0\)</span> : Les produits sont indiscernables. L’ajout de vanille est totalement invisible.</p></li>
<li><p><span class="math inline">\(d^\prime \simeq 1\)</span> : La différence est faible. Seuls les juges les plus sensibles ou les experts ont une chance de détecter la vanille.</p></li>
<li><p><span class="math inline">\(d^\prime &gt; 2\)</span> : La différence est très nette. La vanille modifie profondément le profil aromatique du bissap.</p></li>
</ul>
<p>Dans notre cas <span class="math inline">\(d^\prime \simeq 1.22\)</span>. La valeur obtenue indique une faible différence. L’ajout de vanille est perceptible, mais ce n’est pas une explosion de saveur qui est évidente pour n’importe quel goûteur.</p>
<ul>
<li><p>La valeur de <code>Std. Error</code> est de <span class="math inline">\(0.387\)</span>. C’est l’écart-type de l’erreur. Plus ce chiffre est petit, plus l’estimation du <span class="math inline">\(d^\prime\)</span> est précise.</p></li>
<li><p>Les valeurs <code>Lower</code> et <code>Upper</code> de <span class="math inline">\(0.0\)</span> et <span class="math inline">\(1.95\)</span>, représentent l’intervalle de confiance à 95 %. Il nous dit que le “vrai” <span class="math inline">\(d^\prime\)</span> de la population se situe probablement entre <span class="math inline">\(0\)</span> et <span class="math inline">\(1.95\)</span>.</p></li>
<li><p>Les autres indicateurs :</p>
<ul>
<li><p><code>pc = 0.6167</code> : C’est la proportion de choix corrects (37/60). Environ 62 % des juges ont bien répondu.</p></li>
<li><p><code>pd = 0.2333</code> : C’est la “proportion de détecteurs réels”. Cela suggère que seul environ 23 % du panel a réellement perçu la différence, tandis que les autres ont réussi soit par chance, soit grâce à une intuition très légère.</p></li>
</ul></li>
</ul>
<p><strong>L’effet de l’Expertise et de la la Fatigue</strong></p>
<p>Le profil des sujets est une des variables la plus critique. Dans notre simulation, les experts réussissent mieux que les novices. On cherche à savoir si la vanille est un “marqueur d’expert”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tableau de contigence Expertise / Réussite</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>table_expertise <span class="ot">&lt;-</span> <span class="fu">table</span>(data_duotrio<span class="sc">$</span>expertise, data_duotrio<span class="sc">$</span>reussite)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>table_expertise</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         echec reussi
  Expert     4      8
  Novice    19     29</code></pre>
</div>
</div>
<p>Après avoir validé que la vanille est globalement perçue, nous cherchons à savoir si cette perception est réservée aux palais entraînés. Nous croisons donc la variable expertise avec la reussite via un test du Chi-deux d’indépendance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test du Chi-deux pour voir si l'expertise influence la réussite</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(table_expertise)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table_expertise
X-squared = 0.0044066, df = 1, p-value = 0.9471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Il est préférable d'utiliser un test de Fisher ici car il y auniquement 4 experts qui ont échoué</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(table_expertise)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  table_expertise
p-value = 0.7524
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.1476496 3.3678686
sample estimates:
odds ratio 
 0.7665369 </code></pre>
</div>
</div>
<p>Le test du Chi-deux donne une p-value de <code>0.947</code>, ce qui est très loin du seuil de 0,05. Le test de Fisher donne une p-value de <code>0.7524</code>, ce qui est également bien supérieur à 0.005</p>
<p>L’expertise n’a pas d’influence significative sur la capacité à détecter la vanille dans le bissap pour cette étude. La différence de recette semble donc être perçue de la même manière par un consommateur novice que par un expert.</p>
<p>La fatigue sensorielle est l’ennemi du test Duo-Trio (surtout avec des produits intenses comme le bissap). Un juge fatigué répondra plus souvent au hasard.</p>
<p>Le graphique ci-dessus présente la proportion de réussite selon le niveau de fatigue des juges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_duotrio, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(fatigue), <span class="at">fill =</span> reussite)) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Impact de la fatigue sur la performance"</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Niveau de fatigue (1 à 5)"</span>, </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>) <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="td_palais_p-value_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On observe une tendance surprenante : le taux de reussite semble croître avec le niveau de fatigue. Alors que la théorie suggère que la fatigue sensorielle mène à des réponses aléatoires (50 % de réussite), nos résultats montrent que les sujets les plus fatigués (niveaux 4 et 5) affichent les meilleures performances de détection.</p>
<p><strong>Conclusion</strong> : Ce résultat suggère que dans le cadre du Bissap Istomien, la fatigue n’a pas été un frein à la discrimination. Cela peut s’expliquer par un surcroît de concentration des sujets fatigués ou par une saturation des saveurs dominantes du bissap, facilitant ainsi la perception de la note vanillée par contraste.</p>
<p>Nous avons analysé l’expertise et la fatigue séparément. Cependant, dans la réalité, un juge peut être à la fois expert et fatigué, ou novice et reposé.</p>
</section>
</section>
<section id="test-triangulaire" class="level3">
<h3 class="anchored" data-anchor-id="test-triangulaire">Test Triangulaire</h3>
<p>Le <strong>test triangulaire</strong> est l’un des tests discriminatifs les plus robustes et les plus utilisés en analyse sensorielle. Contrairement au Duo-Trio, il ne repose pas sur une référence identifiée, ce qui augmente l’effort cognitif du sujet mais renforce la puissance statistique du test.</p>
<section id="principe-et-protocole-2" class="level4">
<h4 class="anchored" data-anchor-id="principe-et-protocole-2">Principe et Protocole</h4>
<p>Le test consiste à présenter simultanément trois échantillons codés à un sujet Parmi ces trois échantillons, deux sont identiques et un est différent.</p>
<p>La mission du sujet est d’identifier l’échantillon singulier (celui présenté une seule fois).</p>
<p>Il existe six ordres de présentation possibles pour garantir l’équilibre du plan d’expérience :</p>
<ul>
<li><p>Séries avec deux A : <code>AAB</code>, <code>ABA</code>, <code>BAA</code></p></li>
<li><p>Séries avec deux B : <code>BBA</code>, <code>BAB</code>, <code>ABB</code></p></li>
</ul>
<p>Caractéristiques clés :</p>
<p>Choix forcé : Le sujet juge doit obligatoirement désigner un échantillon, même s’il ne perçoit aucune différence (cela permet d’intégrer le facteur “hasard” de manière stable).</p>
<ul>
<li><p>Probabilité de succès par hasard (p) : 1/3 (soit environ 33,3 %).</p></li>
<li><p>Probabilité d’échec par hasard (q) : 2/3 (soit environ 66,7 %).</p></li>
</ul>
</section>
<section id="avantages-et-indications-2" class="level4">
<h4 class="anchored" data-anchor-id="avantages-et-indications-2">Avantages et Indications</h4>
<p>Ce test est très efficace pour déceler des différences subtiles et couramment utilisé pour déterminer des seuils de perception.</p>
<p>Le test triangulaire offre une <strong>puissance statistique supérieure</strong> au Duo-Trio. En abaissant la probabilité de succès par pur hasard de 50 % (1/2) à 33,3 % (1/3), il permet d’identifier une différence sensorielle avec une plus grande certitude mathématique ou un effectif de juges plus réduit.</p>
<p>Toutefois, ce protocole impose une <strong>charge cognitive et sensorielle</strong> élevée. Le sujet doit effectuer trois comparaisons mentales croisées pour isoler l’intrus, ce qui peut s’avérer particulièrement épuisant lors de l’évaluation de produits intenses, très acides ou sucrés, comme le Bissap.</p>
<p>Enfin, ce test est <strong>déconseillé pour les produits agressifs</strong> provoquant une forte saturation des récepteurs (épices, alcools, astringence marquée). Dans ces conditions, le phénomène de rémanence des premières gorgées risque de fausser la perception de l’échantillon singulier, rendant la dégustation rapidement aléatoire.</p>
</section>
<section id="exploitation-statistique-2" class="level4">
<h4 class="anchored" data-anchor-id="exploitation-statistique-2">Exploitation Statistique</h4>
<p>L’analyse repose sur la comparaison entre le nombre de réponses correctes observées et la distribution de probabilité théorique (Loi Binomiale).</p>
<p><strong>Hypothèse Nulle (H0)</strong> : Les sujets ne perçoivent aucune différence et répondent au hasard. <span class="math display">\[H_0 : \quad p=\frac13\]</span> <strong>Hypothèse Alternative (H1)</strong> : Les sujets perçoivent une différence réelle. <span class="math display">\[H_1 : \quad \frac13\]</span> Comme pour le Duo-Trio, on peut calculer le d′ (d-prime). Pour un même nombre de sujets et un même taux de réussite, le d′ calculé pour un test triangulaire sera différent de celui d’un Duo-Trio car la part du hasard dans le modèle change.</p>
</section>
<section id="application-2" class="level4">
<h4 class="anchored" data-anchor-id="application-2">Application</h4>
<p>L’objectif est de déterminer si l’ajout de vanille crée une différence sensorielle globale, sans orienter le sujet sur un descripteur précis.</p>
<ul>
<li><p>Échantillons : Chaque sujet reçoit 3 verres codés simultanément.</p></li>
<li><p>Composition : Deux verres sont identiques (ex: Nature) et un est différent (ex: Vanille), ou inversement.</p></li>
<li><p>Les 6 ordres de présentation : AAB, ABA, BAA, BBA, BAB, ABB. Ils sont répartis de façon égale entre les sujets.</p></li>
<li><p>Consigne : <strong>« Goûtez les trois échantillons de gauche à droite. Identifiez l’échantillon qui est différent des deux autres.»</strong> (Choix forcé).</p></li>
</ul>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>n_juges <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>ordres_triangle <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"AAB"</span>, <span class="st">"ABA"</span>, <span class="st">"BAA"</span>, <span class="st">"BBA"</span>, <span class="st">"BAB"</span>, <span class="st">"ABB"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>data_triangle <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n_juges,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">expertise =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Expert"</span>, <span class="st">"Novice"</span>), n_juges, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>)),</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordre =</span> <span class="fu">sample</span>(ordres_triangle, n_juges, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>data_triangle<span class="sc">$</span>reussite <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(exp) {</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  prob_succes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(exp <span class="sc">==</span> <span class="st">"Expert"</span>, <span class="fl">0.75</span>, <span class="fl">0.45</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, prob_succes)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(res <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"reussi"</span>, <span class="st">"echec"</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>}, data_triangle<span class="sc">$</span>expertise)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-ebf24f22894ea9c35a7c" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-ebf24f22894ea9c35a7c">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td><\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"1\" data-max=\"60\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","caption":"<caption>Test Triangulaire sur le Bissap<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60],["Novice","Novice","Novice","Novice","Novice","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Novice","Novice","Novice","Novice","Expert","Expert","Novice","Novice","Expert","Expert","Novice","Novice","Expert","Novice","Expert","Novice","Novice","Expert","Expert","Novice","Expert","Novice","Expert","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Expert","Novice"],["ABA","BAB","BAA","BAB","ABA","ABB","BAA","ABB","BBA","BAB","BAA","ABA","BAA","BBA","AAB","ABA","ABA","BAA","AAB","AAB","BBA","BAA","BBA","BAA","BAA","BAB","BAA","BBA","ABB","ABA","AAB","BBA","BAB","BBA","ABB","AAB","BAA","ABA","ABB","ABA","BAB","BAA","AAB","ABA","BAA","AAB","BAA","BBA","BBA","BBA","BAB","BAB","AAB","ABA","BBA","BBA","ABA","BBA","BBA","BBA"],["echec","echec","echec","echec","echec","echec","reussi","reussi","echec","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","echec","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","reussi","echec","reussi","reussi","reussi","echec","echec","reussi","reussi","reussi","reussi","reussi","reussi","reussi","reussi","echec","reussi","reussi","reussi","reussi","echec","reussi","echec","echec","echec","reussi","echec","reussi","echec","reussi"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>expertise<\/th>\n      <th>ordre<\/th>\n      <th>reussite<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"autoWidth":true,"columnDefs":[{"className":"dt-right","targets":1},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"expertise","targets":2},{"name":"ordre","targets":3},{"name":"reussite","targets":4}],"order":[],"orderClasses":false,"orderCellsTop":true}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>n_reussi <span class="ot">&lt;-</span> <span class="fu">sum</span>(data_triangle<span class="sc">$</span>reussite <span class="sc">==</span> <span class="st">"reussi"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>n_total <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data_triangle)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test binomial exact (p = 1/3 pour le triangle)</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> n_reussi, <span class="at">n =</span> n_total, <span class="at">p =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  n_reussi and n_total
number of successes = 31, number of trials = 60, p-value = 0.002557
alternative hypothesis: true probability of success is greater than 0.3333333
95 percent confidence interval:
 0.4034962 1.0000000
sample estimates:
probability of success 
             0.5166667 </code></pre>
</div>
</div>
<p>Ce résultat indique que l’ajout de vanille dans le bissap induit une différence sensorielle statistiquement significative (pvalue = 0,002557 &lt; 0,05).</p>
<p>Bien que le taux de réussite brut (51,6%) puisse paraître modeste, il est nettement supérieur au seuil du hasard spécifique au test triangulaire (33,3%).</p>
<p>L’intervalle de confiance, dont la borne inférieure (0,403) exclut la probabilité de chance (0,33), confirme que les sujets ne répondent pas au hasard.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensR)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du d-prime avec la méthode spécifique "triangle"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">discrim</span>(n_reussi, n_total, <span class="at">method =</span> <span class="st">"triangle"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimates for the triangle discrimination protocol with 31 correct
answers in 60 trials. One-sided p-value and 95 % two-sided confidence
intervals are based on the 'exact' binomial test. 

        Estimate Std. Error   Lower  Upper
pc        0.5167    0.06451 0.38395 0.6477
pd        0.2750    0.09677 0.07592 0.4715
d-prime   1.5529    0.33269 0.75998 2.2209

Result of difference test:
'exact' binomial test:  p-value = 0.002557 
Alternative hypothesis: d-prime is greater than 0 </code></pre>
</div>
</div>
<p>L’estimation du d′ à 1,5529 est particulièrement révélatrice : elle indique une distance sensorielle nette (généralement considérée comme “forte” au-dessus de 1,5). L’erreur standard associée (0,064) suggère une faible variabilité dans les réponses des sujets.</p>
<p>L’intervalle de confiance du d′ ne contenant pas la valeur zéro, on peut affirmer avec certitude que la formulation à la vanille modifie de manière tangible la signature aromatique du produit.</p>
</section>
</section>
<section id="test-p-parmi-n" class="level3">
<h3 class="anchored" data-anchor-id="test-p-parmi-n">Test p parmi n</h3>
<section id="principe-et-protocole-3" class="level4">
<h4 class="anchored" data-anchor-id="principe-et-protocole-3">Principe et Protocole</h4>
<p>Le test p parmi n est un test de discrimination par regroupement. Contrairement au Triangulaire ou au Duo-Trio, il demande au sujet d’isoler un sous-groupe de produits identiques au sein d’un ensemble plus large. Un cas souvent rencontré est le test 2 parmi 5.</p>
<p>On présente simultanément <span class="math inline">\(n\)</span> échantillons codés au sujet. Ce dernier est informé qu’il y a <span class="math inline">\(p\)</span> échantillons A et <span class="math inline">\(n-p\)</span> échantillons B.</p>
<p>La mission du sujet est d’identifier et regrouper les <span class="math inline">\(p\)</span> échantillons appartenant à la même catégorie.</p>
<section id="exemple-du-2-parmi-5" class="level5">
<h5 class="anchored" data-anchor-id="exemple-du-2-parmi-5">Exemple du 2 parmi 5 :</h5>
<p>Le sujet reçoit 5 échantillons. Il sait que 2 sont A et 3 sont B. Il doit désigner les 2 échantillons A.</p>
<p>Ce test est beaucoup plus difficile que les précédents car le nombre de combinaisons possibles augmente drastiquement. La probabilité de succès par hasard (<span class="math inline">\(p\)</span>) est définie par l’inverse des combinaisons <span class="math display">\[\frac{1}{\binom{n}{p}} \qquad \mbox{ où } \qquad \binom{n}{p}=\frac{n!}{(n-p)!p!}\]</span> Pour un test 2 parmi 5, la probabilité de réussir par hasard est de donc de <span class="math inline">\(1 / 10\)</span>, soit seulement <span class="math inline">\(10 \%\)</span>.</p>
</section>
</section>
<section id="avantages-et-indications-3" class="level4">
<h4 class="anchored" data-anchor-id="avantages-et-indications-3">Avantages et Indications</h4>
<p>Ce test est un outil de précision, généralement réservé à des sujets très entraînés.</p>
<ul>
<li><p>Comme la probabilité de réussite par chance est très faible (10 % pour le 2 parmi 5 contre <span class="math inline">\(33 \%\)</span> pour le triangulaire), on peut obtenir des résultats hautement significatifs avec un petit nombre de sujet (souvent moins de 10)</p></li>
<li><p>La fatigue sensorielle est importante. Devoir goûter et comparer 5 échantillons est épuisant pour les récepteurs.</p></li>
<li><p>Le sujet doit garder en mémoire 5 profils aromatiques simultanément, ce qui peut générer de la confusion.</p></li>
</ul>
</section>
<section id="exploitation-statistique-3" class="level4">
<h4 class="anchored" data-anchor-id="exploitation-statistique-3">Exploitation Statistique</h4>
<p>L’analyse suit la loi binomiale, mais avec un paramètre de probabilité <span class="math inline">\(p\)</span> beaucoup plus exigeant.</p>
<ul>
<li><p><strong>Hypothèse Nulle</strong> <span class="math inline">\(H_0\)</span> : Le sujet répond au hasard. Pour un 2 parmi 5, <span class="math display">\[H_0 : \quad p=0,1\]</span></p></li>
<li><p><strong>Hypothèse Alternative</strong> <span class="math inline">\(H_1\)</span> : Le sujet perçoit une différence réelle. Pour un 2 parmi 5, <span class="math display">\[H_1 : \quad p &gt; 0,1\]</span></p></li>
</ul>
</section>
<section id="application-3" class="level4">
<h4 class="anchored" data-anchor-id="application-3">Application</h4>
<p><strong>Test 2 parmi 5 (Bissap Nature vs Vanille)</strong></p>
<p>Dans ce protocole, l’étudiant reçoit 5 échantillons. L’objectif est de regrouper les deux échantillons identiques d’un côté et les trois autres de l’autre.</p>
<ul>
<li><p>Échantillons : 5 verres codés (ex: 2 verres “Vanille” et 3 verres “Nature”).</p></li>
<li><p>Consigne : <strong>« Parmi ces cinq échantillons, deux sont identiques entre eux et trois sont identiques entre eux. Veuillez identifier les deux échantillons qui forment la paire identique. »</strong></p></li>
</ul>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">+</span><span class="dv">1</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-5da4a3e21449d5cc1cf1" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-5da4a3e21449d5cc1cf1">{"x":{"filter":"none","vertical":false,"caption":"<caption>Test 2 parmi 5 sur le Bissap<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],["Novice","Novice","Novice","Novice","Expert","Novice","Novice","Expert","Novice","Novice","Novice","Novice","Novice","Novice","Novice","Expert","Novice","Expert","Novice","Novice","Expert","Novice","Expert","Novice","Novice","Expert","Expert","Novice","Expert","Novice"],["reussi","reussi","echec","echec","reussi","echec","echec","echec","reussi","echec","echec","echec","echec","echec","echec","echec","reussi","reussi","echec","reussi","echec","echec","echec","echec","echec","echec","echec","reussi","reussi","echec"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>expertise<\/th>\n      <th>reussite<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"className":"dt-right","targets":1},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"expertise","targets":2},{"name":"reussite","targets":3}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>n_reussi <span class="ot">&lt;-</span> <span class="fu">sum</span>(data_2parmi5<span class="sc">$</span>reussite <span class="sc">==</span> <span class="st">"reussi"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>n_total <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data_2parmi5)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> n_reussi, <span class="at">n =</span> n_total, <span class="at">p =</span> <span class="fl">0.1</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  n_reussi and n_total
number of successes = 9, number of trials = 30, p-value = 0.00202
alternative hypothesis: true probability of success is greater than 0.1
95 percent confidence interval:
 0.166326 1.000000
sample estimates:
probability of success 
                   0.3 </code></pre>
</div>
</div>
<p>Ce résultat démontre une différence sensorielle hautement significative (p-value = 0,00202) entre les échantillons de Bissap, confirmant que l’ajout de vanille est détecté par le panel avec une certitude statistique très forte.</p>
<p>Bien que le taux de succès brut ne soit que de 30% (9 réussites sur 30), il est trois fois supérieur au seuil du hasard extrêmement bas du test “2 parmi 5” (10%).</p>
<p>L’intervalle de confiance, dont la borne inférieure (0,166) se situe nettement au-dessus de la probabilité de chance (0,10), valide la performance des juges malgré la complexité cognitive de la tâche.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensR)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">discrim</span>(n_reussi, n_total, <span class="at">method =</span> <span class="st">"twofive"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimates for the twofive discrimination protocol with 9 correct
answers in 30 trials. One-sided p-value and 95 % two-sided confidence
intervals are based on the 'exact' binomial test. 

        Estimate Std. Error   Lower  Upper
pc        0.3000    0.08367 0.14735 0.4940
pd        0.2222    0.09296 0.05261 0.4377
d-prime   1.3943    0.32962 0.64883 2.1124

Result of difference test:
'exact' binomial test:  p-value = 0.00202 
Alternative hypothesis: d-prime is greater than 0 </code></pre>
</div>
</div>
<p>L’estimation du d′ à 1,39 indique une distance sensorielle nette et robuste (supérieure au seuil de 1,0 généralement admis pour une différence claire).</p>
<p>L’intervalle de confiance du d′ étant strictement supérieur à zéro, le test “2 parmi 5” s’avère ici extrêmement puissant : malgré un taux de réussite brut de seulement 30%, la faible probabilité de succès par hasard (10%) permet de conclure à une perception réelle et forte de la vanille par les étudiants.</p>
</section>
</section>
</section>
<section id="tests-descriptifs" class="level2">
<h2 class="anchored" data-anchor-id="tests-descriptifs">Tests descriptifs</h2>
<p>Les <strong>tests descriptifs</strong> permettent de caractériser précisément la nature et l’intensité des caractéristiques sensoriels.</p>
<p>Une fois la différence établie par un test triangulaire ou de classement, l’objectif est de mesurer la force de la perception. Cette méthode transforme une sensation subjective en une donnée numérique exploitable.</p>
<section id="test-dintensité" class="level3">
<h3 class="anchored" data-anchor-id="test-dintensité">Test d’intensité</h3>
<section id="principe-et-protocole-4" class="level4">
<h4 class="anchored" data-anchor-id="principe-et-protocole-4">Principe et protocole</h4>
<p>Le sujet évalue l’intensité d’un critère précis (ex : amertume, odeur de vanille, fermeté) sur une échelle linéaire. Contrairement au classement (prochain paragraphe), les échantillons peuvent être présentés un par un.</p>
<p>Le sujet donne une note d’intensité à un echantillon, correspondant à sa perception.</p>
</section>
<section id="avantages-et-indications-4" class="level4">
<h4 class="anchored" data-anchor-id="avantages-et-indications-4">Avantages et Indications</h4>
<p>Ce test est un grand classique des tests sensoriels et nécessite des sujets entraînés pour garantir la répétabilité des notes.</p>
<ul>
<li><p>Il permet une analyse fine.</p></li>
<li><p>Contrairement au classement, on peut dire que A est deux fois plus sucré que B, et pas seulement qu’il l’est “plus”.</p></li>
<li><p>On peut évaluer plusieurs attributs à la suite sur le même échantillon.</p></li>
<li><p>Biais de centrage : Les sujets ont tendance à éviter les extrémités de l’échelle par peur de ne plus avoir de place pour un échantillon plus intense.</p></li>
<li><p>Variabilité inter-individuelle : Certains sujets utilisent tout l’espace de l’échelle, d’autres seulement le milieu. Un entraînement (calibration) est fortement conseillé.</p></li>
</ul>
</section>
<section id="exploitation-statistique-4" class="level4">
<h4 class="anchored" data-anchor-id="exploitation-statistique-4">Exploitation Statistique</h4>
<p>Les notes obtenues sur une échelle sont considérées comme des données quantitatives. On utilise donc les outils de la statistique paramétrique classique.</p>
<ul>
<li><p>Calcul des moyennes et écarts-types : Pour chaque échantillon, on calcule la note moyenne du panel.</p></li>
<li><p>Analyse de Variance (ANOVA) : C’est l’outil roi. Elle permet de tester si les moyennes des notes sont significativement différentes en décomposant la variabilité.</p></li>
<li><p>Test de comparaison de moyennes (Tukey) : Si l’ANOVA est significative, ce test post-hoc permet de comparer les échantillons par paire.</p></li>
</ul>
</section>
<section id="application-4" class="level4">
<h4 class="anchored" data-anchor-id="application-4">Application</h4>
<ul>
<li><p>On se donne une échelle de 0 à 10.</p></li>
<li><p>Échantillons : 3 verres de Bissap (Nature, Vanille 5%, Vanille 10%).</p></li>
<li><p>Consigne : <strong>« Pour chaque échantillon, évaluez l’intensité de l’arôme vanille sur une échelle de 0 (nulle) à 10 (extrêmement forte).»</strong></p></li>
</ul>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">505</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>n_juges <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>produits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Nature"</span>, <span class="st">"Vanille_5"</span>, <span class="st">"Vanille_10"</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>notes_matrix <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n_juges,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nature =</span> <span class="fu">round</span>(<span class="fu">pmin</span>(<span class="fu">pmax</span>(<span class="fu">rnorm</span>(n_juges, <span class="fl">1.5</span>, <span class="fl">1.2</span>), <span class="dv">0</span>), <span class="dv">10</span>), <span class="dv">1</span>),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Vanille_5 =</span> <span class="fu">round</span>(<span class="fu">pmin</span>(<span class="fu">pmax</span>(<span class="fu">rnorm</span>(n_juges, <span class="fl">4.5</span>, <span class="fl">1.5</span>), <span class="dv">0</span>), <span class="dv">10</span>), <span class="dv">1</span>),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Vanille_10 =</span> <span class="fu">round</span>(<span class="fu">pmin</span>(<span class="fu">pmax</span>(<span class="fu">rnorm</span>(n_juges, <span class="fl">7.2</span>, <span class="fl">1.3</span>), <span class="dv">0</span>), <span class="dv">10</span>), <span class="dv">1</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-253d6b3f5fe6f14debe5" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-253d6b3f5fe6f14debe5">{"x":{"filter":"none","vertical":false,"caption":"<caption>Notes d'intensité vanille (Échelle de 0 à 10)<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],[0.2,0,0,0.4,0.9,1,0.4,1.7,2.2,1,0,1.2,0.9,1.3,2.1,1.9,2,3.1,2.5,0.5,0,1,2.7,2.1,2.7,2.2,1,1.7,1.7,3.3],[3,7,4.3,3.9,6.2,3,5.5,3.6,3.3,5.6,2.7,3.9,6.9,5,2.1,4.9,4.3,3.4,3.3,5.6,1.8,3.4,1.8,3.4,4,0.6,4,5.9,4.6,5.1],[10,7.1,8.199999999999999,6.1,7.4,7.6,8.800000000000001,8.4,6.7,8.9,9.9,7.1,8.1,7.1,10,5.3,6.4,5.4,8.199999999999999,9.1,6.3,9.4,5.7,6.4,7.6,7.1,5.9,8.6,7.1,5.9]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>Nature<\/th>\n      <th>Vanille_5<\/th>\n      <th>Vanille_10<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"Nature","targets":2},{"name":"Vanille_5","targets":3},{"name":"Vanille_10","targets":4}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><strong>Analyse Statistique : ANOVA à 2 facteurs</strong></p>
<p>Pour l’intensité, l’outil classique est l’ANOVA. Elle permet de tester l’effet “Produit” tout en retirant l’effet “Juge” (car certains notent toujours sévèrement et d’autres plus largement).</p>
<p>Dans notre protocole, l’indépendance est assurée par le plan d’expérience : chaque étudiant goûte les produits de manière aléatoire. On suppose qu’un sujet n’influence pas la note d’un autre.</p>
<p>L’ANOVA suppose que les erreurs (résidus) suivent une loi normale. On le vérifie visuellement (QQ-plot) et statistiquement (Test de Shapiro-Wilk).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>data_anova <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(notes_matrix, <span class="at">cols =</span> <span class="sc">-</span>id, <span class="at">names_to =</span> <span class="st">"Produit"</span>, <span class="at">values_to =</span> <span class="st">"Note"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>data_anova<span class="sc">$</span>id <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_anova<span class="sc">$</span>id)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>data_anova<span class="sc">$</span>Produit <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_anova<span class="sc">$</span>Produit)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_anova)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  id    Produit     Note
  &lt;fct&gt; &lt;fct&gt;      &lt;dbl&gt;
1 1     Nature       0.2
2 1     Vanille_5    3  
3 1     Vanille_10  10  
4 2     Nature       0  
5 2     Vanille_5    7  
6 2     Vanille_10   7.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle ANOVA : Note ~ Produit + Juge (id)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>modele_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Note <span class="sc">~</span> Produit <span class="sc">+</span> id, <span class="at">data =</span> data_anova)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraction des résidus du modèle</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>residus <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modele_anova)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Shapiro-Wilk</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : Les résidus sont normaux</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(residus)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residus
W = 0.98422, p-value = 0.3484</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation QQ-plot</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residus)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residus, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="td_palais_p-value_files/figure-html/verif-normalite-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>D’apres le test de Shapiro l’hypothèse de normalité est acceptée. De plus les points du graphique (QQ-plot) suivent la ligne rouge, donc tout va bien.</p>
<p>La variabilité des notes doit être à peu près la même pour chaque produit. Pour le vérifier on utilise le Test de Levene.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Levene sur le facteur Produit</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Note <span class="sc">~</span> Produit, <span class="at">data =</span> data_anova)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  2.0532 0.1345
      87               </code></pre>
</div>
</div>
<p>D’apres le test de levene l’hypothèse d’homogénité est donc acceptée.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Que faire si les conditions ne sont pas remplies ?
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’ANOVA est globalement un test robuste, surtout avec un effectif de n=30. Cependant :</p>
<ul>
<li><p>Si la normalité est rejetée, il est possible d’utiliser un test non-paramétrique de Friedman, car il ne nécessite aucune hypothèse sur la distribution des données.</p></li>
<li><p>Si l’homogénéité est rejetée, il est possible d’utiliser une ANOVA avec correction de Welch par exemple.</p></li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_anova)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)    
Produit      2  567.9  283.95 140.860 &lt;2e-16 ***
id          29   34.3    1.18   0.587   0.94    
Residuals   58  116.9    2.02                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Cette ANOVA à deux facteurs démontre un effet Produit tres significatif (p-value extremement faible), confirmant que les variations de concentration en vanille induisent des différences de perception majeures et indiscutables.</p>
<p>À l’inverse, l’effet sujet (id) n’est absolument pas significatif (p-value = 0,94), ce qui est un excellent indicateur de la qualité de notre panel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(modele_anova, <span class="st">"Produit"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Note ~ Produit + id, data = data_anova)

$Produit
                          diff       lwr       upr p adj
Vanille_10-Nature     6.136667  5.254905  7.018428     0
Vanille_5-Nature      2.680000  1.798239  3.561761     0
Vanille_5-Vanille_10 -3.456667 -4.338428 -2.574905     0</code></pre>
</div>
</div>
<p>Le test de Tukey confirme que les différences d’intensité perçues entre les trois échantillons sont toutes hautement significatives (p-value extremement faible).</p>
</section>
</section>
</section>
<section id="test-de-classement" class="level2">
<h2 class="anchored" data-anchor-id="test-de-classement">Test de classement</h2>
<section id="principe-et-protocole-5" class="level3">
<h3 class="anchored" data-anchor-id="principe-et-protocole-5">Principe et protocole</h3>
<p>Le test de classement est une épreuve de comparaison ordonnée. Il ne demande pas de chiffrer une sensation, mais de situer les produits les uns par rapport aux autres selon un critère défini (intensité d’un arôme, couleur, préférence).</p>
<ul>
<li><p>Le sujet reçoit simultanément un ensemble de n échantillons (généralement autour de 5) codés.</p></li>
<li><p>La consigne est de ranger les échantillons par ordre croissant ou décroissant d’intensité pour un attribut donné (ex : “du moins sucré au plus sucré”).</p></li>
<li><p>Contrairement aux tests discriminatifs, le sujet peut goûter les produits plusieurs fois, revenir en arrière et modifier son classement jusqu’à satisfaction.</p></li>
<li><p>Dans le protocole classique, le sujet est obligé de trancher (choix forcé), pas d’égalité, même si la différence lui paraît minime.</p></li>
<li><p>Pour éviter les biais d’ordre (effet de position), les échantillons sont présentés dans des ordres différents selon les sujets.</p></li>
</ul>
</section>
<section id="avantages-et-indications-5" class="level3">
<h3 class="anchored" data-anchor-id="avantages-et-indications-5">Avantages et Indications</h3>
<p>C’est un test assez simple, ce qui en fait un outil de choix pour les premières étapes d’une étude sensorielle.</p>
<ul>
<li><p>Il est très facile à comprendre pour des sujets sans formation préalable.</p></li>
<li><p>Il permet de balayer un grand nombre de prototypes en une seule séance pour éliminer les moins prometteurs.</p></li>
<li><p>Il n’utilise pas d’échelle de notation, il évite le biais des juges “indulgents” ou “sévères”. On ne regarde que le rang.</p></li>
<li><p>On a une perte d’information. En effet si le produit A est classé 1er et le B 2ème, on ne sait pas si l’écart entre les deux est grand ou petit.</p></li>
<li><p>Au-delà de 5 ou 6 échantillons en bouche, la fatigue sensorielle altère la fiabilité du classement.</p></li>
</ul>
</section>
<section id="exploitation-statistique-5" class="level3">
<h3 class="anchored" data-anchor-id="exploitation-statistique-5">Exploitation Statistique</h3>
<p>L’analyse ne porte pas sur des moyennes de notes, mais sur la somme des rangs. Par exemple si un produit est systématiquement classé en 1ère position, sa somme de rangs sera très faible.</p>
<ul>
<li><strong>Calcul de la somme des rangs</strong> ( <span class="math inline">\(R_j\)</span> )</li>
</ul>
<p>Pour chaque échantillon <span class="math inline">\(j\)</span>, on calcule la somme des rangs <span class="math inline">\(r_{i j}\)</span> attribués par les <span class="math inline">\(n\)</span> sujets :</p>
<p><span class="math display">\[
R_j=\sum_{i=1}^n r_{i j}
\]</span> où <span class="math inline">\(r_{i j}\)</span> est le rang donné au produit <span class="math inline">\(j\)</span> par le sujet <span class="math inline">\(i\)</span>. Plus la valeur de <span class="math inline">\(R_j\)</span> est faible, plus le produit est jugé intense (ou préféré) par le panel de sujets.</p>
<ul>
<li><strong>Le Test de Friedman</strong></li>
</ul>
<p>Le test de Friedman est un test non-paramétrique utilisé pour déterminer s’il existe des différences significatives entre au moins deux échantillons au sein d’un bloc (le panel).</p>
<ul>
<li><strong>Hypothèse Nulle</strong> <span class="math inline">\(H_0\)</span> : Il n’y a pas de différence entre les produits, les rangs sont distribués de manière aléatoire.</li>
</ul>
<p><span class="math display">\[
H_0: \qquad R_1=R_2=\ldots=R_j
\]</span></p>
<ul>
<li><strong>Hypothèse Alternative</strong> ( <span class="math inline">\(H_1\)</span> ) : Au moins un produit se distingue significativement des autres.</li>
</ul>
<p>La statistique de Friedman suit approximativement une loi du <span class="math inline">\(\chi^2\)</span> à (<span class="math inline">\(j-1\)</span>) degrés de liberté. Si la p-value associée est inférieure au seuil <span class="math inline">\(\alpha\)</span>, on rejette <span class="math inline">\(H_0\)</span>.</p>
<ul>
<li><strong>Analyse Post-hoc : Test de Nemenyi</strong></li>
</ul>
<p>Lorsque le test de Friedman révèle une différence significative, il ne précise pas quels produits s’écartent les uns des autres. On procède alors à une comparaison par paires en utilisant le Test de Nemenyi (ou de Wilcoxon-Wilcox).</p>
<p>On calcule la <strong>P</strong>lus <strong>P</strong>etite <strong>D</strong>ifférence <strong>S</strong>ignificative (PPDS), également appelée valeur critique. Si l’écart entre les sommes de rangs de deux produits est supérieur à cette valeur, la différence est considérée comme statistiquement significative :</p>
<p><span class="math display">\[
\left|R_A-R_B\right|&gt;P P D S
\]</span></p>
</section>
<section id="application-5" class="level3">
<h3 class="anchored" data-anchor-id="application-5">Application</h3>
<p><strong>Classement d’intensité</strong></p>
<p>Échantillons : 4 verres de Bissap avec des dosages de vanille croissants :</p>
<ul>
<li><p>A : Nature (0% vanille)</p></li>
<li><p>B : Vanille Faible (5%)</p></li>
<li><p>C : Vanille Moyenne (10%)</p></li>
<li><p>D : Vanille Forte (20%)</p></li>
</ul>
<p>La consigne est : <strong>« Goûtez les quatre échantillons. Classez-les du moins vanillé (rang 1) au plus vanillé (rang 4). Les égalités ne sont pas autorisés. »</strong></p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code pour générer nos données
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">404</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>n_juges <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>produits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>gen_rank <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  score_theo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">4</span>, <span class="at">sd =</span> <span class="fl">0.8</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rank</span>(score_theo)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>ranks_matrix <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">replicate</span>(n_juges, <span class="fu">gen_rank</span>()))</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>data_classement <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(ranks_matrix)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data_classement) <span class="ot">&lt;-</span> produits</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>data_classement <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n_juges, data_classement)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-af8c6e22e4232e91a38f" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-af8c6e22e4232e91a38f">{"x":{"filter":"none","vertical":false,"caption":"<caption>Test de classement de l'intensité vanille sur le Bissap<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],[1,1,1,1,1,3,2,1,1,1,1,1,1,1,1,1,2,1,1,2,1,1,2,1,1,1,1,1,1,1],[2,3,4,3,2,1,1,2,2,2,3,3,2,2,2,2,1,2,3,1,2,2,1,2,2,2,3,2,2,3],[3,2,2,2,4,2,3,4,3,4,2,2,3,3,3,3,4,3,4,4,3,4,4,3,3,3,2,4,3,2],[4,4,3,4,3,4,4,3,4,3,4,4,4,4,4,4,3,4,2,3,4,3,3,4,4,4,4,3,4,4]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>A<\/th>\n      <th>B<\/th>\n      <th>C<\/th>\n      <th>D<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"id","targets":1},{"name":"A","targets":2},{"name":"B","targets":3},{"name":"C","targets":4},{"name":"D","targets":5}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Somme des rangs par produit</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>somme_rangs <span class="ot">&lt;-</span> <span class="fu">colSums</span>(data_classement[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>somme_rangs</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  A   B   C   D 
 36  64  91 109 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Friedman</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>mat_friedman <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(data_classement[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">friedman.test</span>(mat_friedman)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Friedman rank sum test

data:  mat_friedman
Friedman chi-squared = 61.08, df = 3, p-value = 3.455e-13</code></pre>
</div>
</div>
<p>Ce résultat est extrêmement significatif (p-value est tres tres faible), démontrant que le panel d’étudiants perçoit une hiérarchie d’intensité de la vanille qui ne doit absolument rien au hasard.</p>
<p>Ce test global valide la pertinence de notre gamme de dosages : les paliers de vanille (A &lt; B &lt; C &lt; D) sont sensoriellement bien étalés, ce qui justifie l’étape suivante de comparaison par paires (Test de Nemenyi) pour identifier précisément où se situent les seuils de différenciation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PMCMRplus)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>data_posthoc <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(mat_friedman)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>data_posthoc<span class="sc">$</span>Sujet <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_posthoc))</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>data_posthoc_clean <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(data_posthoc, </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">cols =</span> <span class="sc">-</span>Sujet, </span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">names_to =</span> <span class="st">"Produit"</span>, </span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">values_to =</span> <span class="st">"Rang"</span>)</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>data_posthoc_clean<span class="sc">$</span>Produit <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_posthoc_clean<span class="sc">$</span>Produit)</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>data_posthoc_clean<span class="sc">$</span>Sujet <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_posthoc_clean<span class="sc">$</span>Sujet)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a><span class="fu">frdAllPairsNemenyiTest</span>(Rang <span class="sc">~</span> Produit <span class="sc">|</span> Sujet, <span class="at">data =</span> data_posthoc_clean)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  A       B       C    
B 0.026   -       -    
C 2.3e-07 0.035   -    
D 1.8e-12 4.0e-05 0.273</code></pre>
</div>
</div>
<p>Ce résultat de comparaisons par paires (test de Nemenyi) apporte la preuve statistique de la hiérarchie de perception de la vanille dans ces recettes de Bissap. Avec une p-value globale très faible, le test confirme que les étudiants ne classent pas les verres au hasard.</p>
<p>Interprétation des p-values au seuil <span class="math inline">\(\alpha\)</span> de 5 %.</p>
<p>Le tableau se lit par intersection entre les échantillons (A: Nature, B: Faible, C: Moyenne, D: Forte).</p>
<ul>
<li><p>L’échantillon A (Nature) est significativement différent de tous les autres (p-value = 0,026 pour B, et des valeurs quasi nulles pour C et D). Cela prouve que même la plus faible dose de vanille (B) est détectée par rapport au témoin.</p></li>
<li><p>L’échantillon B se distingue nettement de C (0,035) et de D (0,00004). Le panel des sujets perçoit donc bien les paliers de concentration.</p></li>
<li><p>Il n’y a pas de différence significative entre C (Moyenne) et D (Forte) (p-value = 0,273).</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<style>

.pdf-download-in-toc {

  text-align: center;

  margin-top: 1rem;

}



.pdf-download-in-toc a {

  display: inline-flex;

  align-items: center;

  gap: 0.4em;

  padding: 0.4em 0.8em;

  background-color: #f5f5f5;

  border-radius: 8px;

  text-decoration: none;

  font-size: 0.9em;

  color: #333;

  transition: background-color 0.2s ease;

}



.pdf-download-in-toc a:hover {

  background-color: #e0e0e0;

}



.pdf-download-in-toc svg {

  width: 18px;

  height: 18px;

  fill: currentColor;

}

</style>



<script>

document.addEventListener("DOMContentLoaded", function() {

  // essaie plusieurs sélecteurs possibles pour trouver le TOC

  const toc =

    document.querySelector(".quarto-toc-container") ||

    document.querySelector(".toc") ||

    document.querySelector("nav#TOC") ||

    document.querySelector(".sidebar nav");



  if (toc) {

    // Ajouter le logo avant le TOC

    const logo = document.createElement("img");

    logo.src = "img/Logo_simple_ISTOM_Couleurs_HD.png"; // adapte si besoin

    logo.alt = "Logo ISTOM";

    logo.style.cssText = "display:block;height:70px;margin:0 0 1rem 1rem";

    

    toc.parentNode.insertBefore(logo, toc);

    

    // S'assurer que le TOC est sous le logo

    toc.style.clear = "both";



    // Ajouter le bouton PDF

    //const div = document.createElement("div");

    //div.className = "pdf-download-in-toc";

    //div.innerHTML = `

      //<a href="doc/FROMAGEOT_Clementine_MFE_P111_2025.pdf" target="_blank">

        //<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">

          //<path d="M12 16l4-5h-3V4h-2v7H8l4 5zm8 2H4v2h16v-2z"/>

        //</svg>

        //Mémoire C. Fromageot

      //</a>

    //`;

    //toc.appendChild(div);

  } else {

    console.warn("TOC non trouvé — vérifie le thème ou la structure HTML");

  }

});

</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>